---
#-------------------------------
# General Site Settings

title: Figure317
logo:
author: JongwanKim
description: this is meta description
email: jongwankim@snu.ac.kr
phone: +82 10-4019-1133
github: https://github.com/figurekim317
address: 15, Maebong-gil, Seongdong-gu, Seoul, Republic of Korea
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Blog, link: "/blog" }
  - { name: Contact, link: "/contact" }

plugins:
  - jekyll-spaceship
  - jekyll-mathjax
  - jekyll-sitemap


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Jongwan Kim<br> ML/DL Engineer

social:
  - { icon: "ti-github", link: "https://github.com/figurekim317" }
#  - { icon: "ti-instagram", link: "#" }
#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: In the pursuit of improving the world, <br>I am consistently and gradually making sincere progress.
blurb-btn-link: "/about"
blurb-btn-name: know more


# About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: ML/DL algorithm, color: "#fdb157", value: "90%" }
  - { name: python, color: "#9473e6", value: "60%" }
  - { name: C++, color: "#bdecf6", value: "80%" }
  - { name: openCV, color: "#bdecf6", value: "80%" }
  - { name: ROS, color: "#ffbcaa", value: "70%" }
  - { name: Gstreamer, color: "#fdb157", value: "90%" }
  - { name: JAVA, color: "#9473e6", value: "60%" }
  - { name: Confluence \& JIRA, color: "#bdecf6", value: "80%" }
  - { name: Adobe, color: "#ffbcaa", value: "70%" }


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Accelerator Control & Program Engineer,
      icon: "icon-1.png",
      date: "2014 - 2017",
      organization: "CERN, Geneve, Switzerland",
    }
  - {
      name: Perception Engineer,
      icon: "icon-2.png",
      date: "2023",
      organization: "Neubility",
    }


#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Autonomous Driving Dev Course,
      date: "2023",
      organization: "Programmers",
    }
  - {
      name: ECE doctoral course completion,
      date: "2022",
      organization: "Seoul National University",
    }
  - {
      name: ECE master degree,
      date: "2020",
      organization: "Seoul National University",
    }
  - {
      name: EEE bachelor degree,
      date: "2014",
      organization: "Sungkyunkwan University",
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "/fpost/1/"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Model compression", type: "On device" }
  - { title: "Object detection", type: "computer vision" }
  - { title: "Segmentation", type: "computer vision" }
  - { title: "Optimization", type: "optimization" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "/fpost/1/"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Contact Section

# contact-title: Contact Info
# contact-email: steve.fruits@email.com
