---
#-------------------------------
# General Site Settings

title: Figure317
logo:
author: Dohyeong Kim
description: this is meta description
email: figurekim317@gmail.com
# phone: +82 10-7130-1776
github: https://github.com/figurekim317
#address: 15, Maebong-gil, Seongdong-gu, Seoul, Republic of Korea
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Blog, link: "/blog" }
  - { name: Contact, link: "/contact" }

plugins:
  - jekyll-spaceship
  - jekyll-mathjax
  - jekyll-sitemap


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Dohyeong Kim<br> ML/DL Engineer

social:
  - { icon: "fa-brands fa-github", link: "https://github.com/figurekim317" }
  - { icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/figure317" }

#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: In the pursuit of improving the world, <br>I am consistently and gradually making sincere progress.
blurb-btn-link: "/about"
blurb-btn-name: know more


# About Page

#-------------------------------
# Skills Section

#skills-title: Skills
#skills:
#  - { name: Model Compression, color: "#B2A4FF", value: "80%" }
#  - { name: Computer Vision, color: "#B2A4FF", value: "80%" }
#  - { name: Optimization, color: "#B2A4FF", value: "80%" }
#  - { name: Generative model, color: "#B2A4FF", value: "70%" }

#  - { name: PYTHON, color: "#FFB4B4", value: "70%" }
#  - { name: C++, color: "#FFB4B4", value: "70%" }
#  - { name: OpenCV, color: "#FFB4B4", value: "60%" }
#  - { name: ROS, color: "#FFB4B4", value: "60%" }

#  - { name: Github, color: "#FFDEB4", value: "90%" }
#  - { name: Confluence & JIRA, color: "#FFDEB4", value: "90%" }
#  - { name: Gstreamer, color: "#FFDEB4", value: "50%" }
#  - { name: Adobe, color: "#FFDEB4", value: "80%" }

skills-title: Skills
skills:
  - { name: Computer Vision & Robotics, color: "#B2A4FF", value: "90%" }
  - { name: Model Compression & Deployment, color: "#B2A4FF", value: "90%" }
  - { name: Reinforcement Learning, color: "#B2A4FF", value: "80%" }
  - { name: LLM & Foundation Models, color: "#B2A4FF", value: "85%" }

  - { name: Docker, color: "#FFDEB4", value: "90%" }
  - { name: TensorRT, color: "#FFDEB4", value: "85%" }
  - { name: CI/CD, color: "#FFDEB4", value: "85%" }
  - { name: Backend & Frontend, color: "#FFDEB4", value: "85%" }

  - { name: PYTHON, color: "#FFB4B4", value: "85%" }
  - { name: C++, color: "#FFB4B4", value: "80%" }
  - { name: GitHub Actions, color: "#FFB4B4", value: "80%" }
  - { name: ROS, color: "#FFB4B4", value: "70%" }





#-------------------------------
# Research Section

#research-title: Research Area
#researches:
#  - { name: Model Compression, color: "#B2A4FF", value: "80%" }
#  - { name: Computer Vision, color: "#B2A4FF", value: "80%" }
#  - { name: Optimization, color: "#B2A4FF", value: "80%" }
#  - { name: Generative model, color: "#B2A4FF", value: "70%" }

#  - { name: PYTHON, color: "#FFB4B4", value: "70%" }
#  - { name: C++, color: "#FFB4B4", value: "70%" }
#  - { name: OpenCV, color: "#FFB4B4", value: "60%" }
#  - { name: ROS, color: "#FFB4B4", value: "60%" }

#  - { name: Github, color: "#FFDEB4", value: "90%" }
#  - { name: Confluence & JIRA, color: "#FFDEB4", value: "90%" }
#  - { name: Gstreamer, color: "#FFDEB4", value: "50%" }
#  - { name: Adobe, color: "#FFDEB4", value: "80%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: CTO,
      icon: "rga.png",
      date: "May 2023 – Oct 2024",
      team: "RGA Inc.",
      organization: "RGA Inc., Seoul, South Korea",
    }
  - {
      name: AI Engineer,
      icon: "neubility.png",
      date: "Feb 2023 – Apr 2023",
      team: "Perception team",
      organization: "Neubility, Seoul, South Korea",
    }
  - {
      name: Student Researcher,
      icon: "kist.png",
      date: "May 2022 – Aug 2022",
      team: "Artificial Brain Convergence Research Center",
      organization: "KIST, Seoul, South Korea",
    }
  - {
      name: Researcher,
      icon: "cern.png",
      date: "Jul 2015 – Aug 2017",
      team: "RF2 Team",
      organization: "CERN, Geneva, Switzerland",
    }


#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Programmers Dev Course in Autonomous Driving (Planning & Control),
      date: "Mar 2023 – Sep 2023",
      organization: "Programmers",
    }
  - {
      name: Integrated MS/PhD Program in Artificial Intelligence,
      date: "Mar 2018 – Feb 2023",
      organization: "Seoul National University",
      gpa: "GPA: 3.9 / 4.3",
    }
  - {
      name: BSE in Electronic and Electrical Engineering,
      date: "Mar 2008 – Feb 2014",
      organization: "Sungkyunkwan University",
      gpa: "GPA: 4.24 / 4.5 (Summa Cum Laude, Top 0.16%)",
    }




#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "fpost/rga/preview_img/depth.png"
    url: "/fpost/rga/depth_estimation/"

  - image: "fpost/rga/preview_img/face.png"
    url: "/fpost/rga/face_recognition/"

  - image: "fpost/rga/preview_img/mimic.png"
    url: "/fpost/rga/mimic_animal/"

  - image: "fpost/rga/preview_img/object.png"
    url: "/fpost/rga/object_detection/"

  - image: "fpost/neubility/preview_img/object.png"
    url: "/fpost/neubility/object_detection/"

  - image: "fpost/snu/preview_img/snn.png"
    url: "/fpost/snu/snn/"

  - image: "fpost/snu/preview_img/snn.png"
    url: "/fpost/snu/snn_project/"

  - image: "fpost/snu/preview_img/battery.png"
    url: "/fpost/snu/battery/"

  - image: "fpost/snu/preview_img/anomaly.png"
    url: "/fpost/snu/anomaly_detection/"

# Portfolio Page
portfolio-label:
  - { title: "RGA Inc.", type: "RGA"}
  - { title: "Neubility", type: "Neubility"}
  - { title: "SNU", type: "SNU"}
  - { title: "Foundation", type: "Foundation"}
  - { title: "Detection", type: "Detection"}
  - { title: "Depth", type: "Depth"}
  - { title: "Compression", type: "Compression"}
  - { title: "RL", type: "RL"}
  - { title: "LLM", type: "LLM"}

portfolio-items:
  - image: "fpost/rga/preview_img/depth.png"
    url: "/fpost/rga/depth_estimation/"
    portfolio-type:
      - type: "Detection"
      - type: "Compression"
      - type: "Depth"
      - type: "RGA"
      - type: "Foundation"

  - image: "fpost/rga/preview_img/face.png"
    url: "/fpost/rga/face_recognition/"
    portfolio-type:
      - type: "RGA"
      - type: "Detection"
      - type: "Foundation"
      - type: "Compression"

  - image: "fpost/rga/preview_img/mimic.png"
    url: "/fpost/rga/mimic_animal/"
    portfolio-type:
      - type: "RGA"
      - type: "RL"

  - image: "fpost/rga/preview_img/object.png"
    url: "/fpost/rga/object_detection/"
    portfolio-type:
      - type: "RGA"
      - type: "Detection"
      - type: "Compression"

  - image: "fpost/neubility/preview_img/object.png"
    url: "/fpost/neubility/object_detection/"
    portfolio-type:
      - type: "Neubility"
      - type: "Detection"
      - type: "Compression"
      - type: "Depth"

  - image: "fpost/snu/preview_img/snn.png"
    url: "/fpost/snu_snn/"
    portfolio-type:
      - type: "Compression"
      - type: "SNU"
      - type: "Detection"

  - image: "fpost/snu/preview_img/snn.png"
    url: "/fpost/snu/snn_project/"
    portfolio-type:
      - type: "SNU"
      - type: "Detection"

  - image: "fpost/snu/preview_img/anomaly.png"
    url: "/fpost/snu/anomaly_detection/"
    portfolio-type:
      - type: "Detection"
      - type: "Compression"
      - type: "SNU"

  - image: "fpost/snu/preview_img/battery.png"
    url: "/fpost/snu/battery/"
    portfolio-type:
      - type: "SNU"

  
#-------------------------------
# Blog Section
blog-tags:
  - { title: "Model Compression", type: "model compression" }
  - { title: "Object detection", type: "object detection" }
  - { title: "Segmentation", type: "segmentation" }
  - { title: "Diffusion", type: "diffusion" }
  - { title: "GAN", type: "GAN"}
  - { title: "Autonomy-driving", type: "Autonomy-driving"}
  - { title: "Dev course", type: "dev"}
  - { title: "Coding", type: "coding"}

  
#-------------------------------
# Contact Section

# contact-title: Contact
contact-email: figurekim317@gmail.com
