---
#-------------------------------
# General Site Settings

title: Figure317
logo:
author: Dohyeong Kim
description: this is meta description
email: figurekim317@gmail.com
# phone: +82 10-7130-1776
github: https://github.com/figurekim317
#address: 15, Maebong-gil, Seongdong-gu, Seoul, Republic of Korea
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Blog, link: "/blog" }
  - { name: Contact, link: "/contact" }

plugins:
  - jekyll-spaceship
  - jekyll-mathjax
  - jekyll-sitemap


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Dohyeong Kim<br> ML/DL Engineer

social:
  - { icon: "ti-github", link: "https://github.com/figurekim317" }
#  - { icon: "ti-likedin", link: "#" }
#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: In the pursuit of improving the world, <br>I am consistently and gradually making sincere progress.
blurb-btn-link: "/about"
blurb-btn-name: know more


# About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Model Compression, color: "#B2A4FF", value: "80%" }
  - { name: Computer Vision, color: "#B2A4FF", value: "80%" }
  - { name: Optimization, color: "#B2A4FF", value: "80%" }
  - { name: Generative model, color: "#B2A4FF", value: "70%" }

  - { name: PYTHON, color: "#FFB4B4", value: "70%" }
  - { name: C++, color: "#FFB4B4", value: "70%" }
  - { name: OpenCV, color: "#FFB4B4", value: "60%" }
  - { name: ROS, color: "#FFB4B4", value: "60%" }

  - { name: Github, color: "#FFDEB4", value: "90%" }
  - { name: Confluence & JIRA, color: "#FFDEB4", value: "90%" }
  - { name: Gstreamer, color: "#FFDEB4", value: "50%" }
  - { name: Adobe, color: "#FFDEB4", value: "80%" }

# Skills Section

research-title: Research Area
research:
  - { name: Model Compression, color: "#B2A4FF", value: "80%" }
  - { name: Computer Vision, color: "#B2A4FF", value: "80%" }
  - { name: Optimization, color: "#B2A4FF", value: "80%" }
  - { name: Generative model, color: "#B2A4FF", value: "70%" }

  - { name: PYTHON, color: "#FFB4B4", value: "70%" }
  - { name: C++, color: "#FFB4B4", value: "70%" }
  - { name: OpenCV, color: "#FFB4B4", value: "60%" }
  - { name: ROS, color: "#FFB4B4", value: "60%" }

  - { name: Github, color: "#FFDEB4", value: "90%" }
  - { name: Confluence & JIRA, color: "#FFDEB4", value: "90%" }
  - { name: Gstreamer, color: "#FFDEB4", value: "50%" }
  - { name: Adobe, color: "#FFDEB4", value: "80%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: CTO,
      icon: "rga.png",
      date: "May 2023 – Oct 2024",
      team: "RGA Inc.",
      organization: "RGA Inc., Seoul, South Korea",
    }
  - {
      name: AI Perception Engineer,
      icon: "neubility.png",
      date: "Feb 2023 – Apr 2023",
      team: "Perception",
      organization: "Neubility, Seoul, South Korea",
    }
  - {
      name: Student Researcher,
      icon: "kist.png",
      date: "May 2022 – Aug 2022",
      team: "Artificial Brain Convergence Research Center",
      organization: "KIST, Seoul, South Korea",
    }
  - {
      name: Researcher,
      icon: "cern.png",
      date: "Jul 2015 – Aug 2017",
      team: "RF2 Team",
      organization: "CERN, Geneva, Switzerland",
    }


#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Programmers Dev Course in Autonomous Driving (Planning & Control),
      date: "Mar 2023 – Sep 2023",
      organization: "Programmers",
    }
  - {
      name: Integrated MS/PhD Program in Artificial Intelligence,
      date: "Mar 2018 – Feb 2023",
      organization: "Seoul National University",
      gpa: "GPA: 3.9 / 4.3",
    }
  - {
      name: BSE in Electronic and Electrical Engineering,
      date: "Mar 2008 – Feb 2014",
      organization: "Sungkyunkwan University",
      gpa: "GPA: 4.24 / 4.5 (Summa Cum Laude, Top 0.16%)",
    }




#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "/fpost/1/"

  - image: "assets/images/portfolio/item-2.png"
    url: "/fpost/2/"

  - image: "assets/images/portfolio/item-3.png"
    url: "/fpost/3/"

  - image: "assets/images/portfolio/item-4.png"
    url: "/fpost/4/"

  - image: "assets/images/portfolio/item-5.png"
    url: "/fpost/5/"

# Portfolio Page
portfolio-label:
  - { title: "Model Compression", type: "Model compression" }
  - { title: "Object detection", type: "Object detection" }
  - { title: "Segmentation", type: "Segmentation" }
  - { title: "Optimization", type: "Optimization" }
  - { title: "SNN", type: "SNN"}
  - { title: "Anomaly", type: "Anomaly"}
  - { title: "Sequence", type: "Sequence"}

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "/fpost/1/"
    portfolio-type:
      - type: "Model compression"
      - type: "Object detection"
      - type: "Optimization"
      - type: "Segmentation"

  - image: "assets/images/portfolio/item-2.png"
    url: "/fpost/2/"
    portfolio-type:
      - type: "Model compression"
      - type: "Object detection"
      - type: "SNN"

  - image: "assets/images/portfolio/item-3.png"
    url: "/fpost/3/"
    portfolio-type:
      - type: "SNN"
      - type: "Object detection"

  - image: "assets/images/portfolio/item-4.png"
    url: "/fpost/4/"
    portfolio-type:
      - type: "Model compression"
      - type: "Object detection"
      - type: "Segmentation"
      - type: "Anomaly"

  - image: "assets/images/portfolio/item-5.png"
    url: "/fpost/5/"
    portfolio-type:
      - type: "Sequence"
      - type: "Anomaly"

#-------------------------------
# Blog Section
blog-tags:
  - { title: "Model Compression", type: "model compression" }
  - { title: "Object detection", type: "object detection" }
  - { title: "Segmentation", type: "segmentation" }
  - { title: "Diffusion", type: "diffusion" }
  - { title: "GAN", type: "GAN"}
  - { title: "Autonomy-driving", type: "Autonomy-driving"}
  - { title: "Dev course", type: "dev"}
  - { title: "Coding", type: "coding"}

  
#-------------------------------
# Contact Section

# contact-title: Contact
contact-email: figurekim317@gmail.com
